<?php

namespace LaravelTheme;

use Illuminate\Support\ServiceProvider as LaravelServiceProvider;

class ServiceProvider extends LaravelServiceProvider
{
    protected $defer = true;

    public function boot()
    {

    }

    public function register()
    {

    }

    public function provides()
    {
        return parent::provides(); // TODO: Change the autogenerated stub
    }

}
